name: Todo test
on: [push]

concurrency:
  group: "${{ github.workflow}}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Load environment variables
        run: |
          cat .env | xargs -I {} echo "export {}" >> .env
          
          DJANGO_SETTINGS_MODULE: todo.settings
      - name: Create and migrate database
        run: |
          python manage.py makemigrations
          python manage.py migrate
      - name: Run tests
        run: |
          python manage.py test